# Tugas SVD


## Persiapan

Install dan Import Packages

In [ ]:
!pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client  

# Stem for Indonesian Language
!pip install Sastrawi

In [23]:
import pandas as pd
import numpy as np
from numpy import array


#for text pre-processing
import re, string
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# stemming for Indonesian Language
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

nltk.download('punkt')
nltk.download('stopwords')


#for model-building
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler  # to standardize the features
from sklearn.decomposition import PCA  # to apply PCA
import seaborn as sns  # to plot the heat maps


#for word embedding
import gensim
from gensim.models import Word2Vec

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
from sklearn.utils.extmath import randomized_svd
from nltk.tokenize import RegexpTokenizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## Crawl Komentar dari YouTube

In [3]:
api = pd.read_json('/content/drive/MyDrive/prosaindata/source/tasks/assets/api.json')

In [4]:
# Python program for extracting YouTube comments using YouTube API  
# import all the required libraries  
import os  
import google.auth  
import googleapiclient.discovery 
    
api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = "AIzaSyCRZrqdGB8ZxRVPu_xw_6tFxct08BZt4D8"

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey = DEVELOPER_KEY) 
    
# Set video ID  
# source https://www.youtube.com/watch?v=LAt-RUDh7gg
video_id = 'LAt-RUDh7gg' 
    
# Call the API to get comments  
comments = []
results = youtube.commentThreads().list(  
    part = 'snippet',  
    textFormat='plainText',
    videoId=video_id
)

get_results = results.execute()

# Loop through each comment and append to comments list  
while get_results:  
    for item in get_results['items']:  
        comment = item['snippet']['topLevelComment']['snippet']['textDisplay']  
        comments.append(comment)  
            
    # Check if there are more comments and continue iterating  
    if 'nextPageToken'in get_results:  
        get_results = youtube.commentThreads().list(  
            part = 'snippet',
            videoId=video_id,
            textFormat='plainText',
            pageToken = get_results['nextPageToken']
        ).execute()
    else:
        break

In [5]:
df = pd.DataFrame((comments), columns=["comment"])

In [6]:
df.info

<bound method DataFrame.info of                                                comment
0    survai bohoong, rakyat dah cerdas tahun2 yg la...
1                                    Alahsurve survean
2       Surpey pesanan Tetap anies yg terbaik for Ri 1
3                  Sekali Anies tetap Anies hidup NKRI
4                             Sekali Anies tetap Anies
..                                                 ...
709                          charta politika,hhhhhh 😂🤣
710  Klo anies presiden, hutang negara dipastikan l...
711  Berarti fix putaran kedua ada Ganjar dan Anies...
712          Muka muka calon banyakin utang negara 🤣🤣🤣
713                                    Assalamualaikum

[714 rows x 1 columns]>

In [7]:
df.head(10)

comment
0  survai bohoong, rakyat dah cerdas tahun2 yg la...
1                                  Alahsurve survean
2     Surpey pesanan Tetap anies yg terbaik for Ri 1
3                Sekali Anies tetap Anies hidup NKRI
4                           Sekali Anies tetap Anies
5  Dimana2 Anis selalu dikecilkan tapi buktinya a...
6        Pasti survei pa Prabowo,tapi yg naik ga tau
7                                  Sok lah mang Anis
8  Pdip ganjar puang kenapa bigun cari pasagan co...
9  Jagan di atik 2 degan surpai tegakan hatimu  a...

In [8]:
comments_col = df["comment"]

## Preprocessing

In [9]:
def preprocess(text):
    """convert to lowercase, strip and remove punctuations"""
    text = text.lower() 

    # replace all one or more space to one space
    text = re.sub(r'^\w+','',text)

    # remove whitespace
    text = text.strip() 
    # compile pattern that have `<.*?>` then replace with ''
    text = re.compile('<.*?>').sub('', text) 

    # compile pattern that have punctuation !"#$%&'()*+, -./:;<=>?@[\]^_`{|}~ then replace with ' '
    text = re.compile('[%s]' % re.escape(string.punctuation)).sub(' ', text)

    # replace all one or more space to one space
    text = re.sub('\s+', ' ', text)

    # replace all number 0-9 to one space
    text = re.sub(r"\d+", "", text)

    # replace all first word or space in the beginning of line to ''
    text = re.sub(r'[^\w\s]', '', str(text).lower().strip())

    # replace all digits to one space
    text = re.sub(r'\d',' ',text) 

    # replace all one or more space to one space
    text = re.sub(r'\s+',' ',text)

    return text

def stopword(string):
    """Stopword removal like I, The, An, be, is, etc"""
    a = [i for i in string.split() if i not in stopwords.words('indonesian')]
    return ' '.join(a)

Bersihkan kalimat dari tanda baca dan pola kata yang tidak penting

In [10]:
preprocessed_comments = []
for text in comments_col:
    preprocessed_comments.append(preprocess(str(text)))

In [11]:
preprocessed_comments = pd.Series(preprocessed_comments)

In [12]:
preprocessed_comments

0      bohoong rakyat dah cerdas tahun yg lalu trnyat...
1                                                survean
2                  pesanan tetap anies yg terbaik for ri
3                           anies tetap anies hidup nkri
4                                      anies tetap anies
                             ...                        
709                                     politika hhhhhh 
710    anies presiden hutang negara dipastikan lunas ...
711    fix putaran kedua ada ganjar dan anies putaran...
712                    muka calon banyakin utang negara 
713                                                     
Length: 714, dtype: object

Hapus Stopword

In [13]:
preprocessed_stopword_comments = []
for text in preprocessed_comments:
    preprocessed_stopword_comments.append(stopword(str(text)))

In [14]:
preprocessed_stopword_comments = pd.Series(preprocessed_stopword_comments)

In [15]:
preprocessed_stopword_comments

0      bohoong rakyat dah cerdas yg trnyata bayaran l...
1                                                survean
2                        pesanan anies yg terbaik for ri
3                                 anies anies hidup nkri
4                                            anies anies
                             ...                        
709                                      politika hhhhhh
710    anies presiden hutang negara lunas dana buzzer...
711    fix putaran ganjar anies putaran final suara p...
712                     muka calon banyakin utang negara
713                                                     
Length: 714, dtype: object

In [16]:
# sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def to_base_word(string):
    """Change words to base words"""
    string = string.split()
    text = [stemmer.stem(word) for word in string]
    return ' '.join(text)

In [17]:
removed_stopword_comments = []
for text in preprocessed_stopword_comments:
    removed_stopword_comments.append(stopword(str(text)))

cleaned_comments = []
for text in removed_stopword_comments:
    cleaned_comments.append(to_base_word(str(text)))

In [18]:
cleaned_comments = pd.Series(cleaned_comments)

In [19]:
cleaned_comments

0      bohoong rakyat dah cerdas yg trnyata bayar lih...
1                                                survean
2                             pesan anies yg baik for ri
3                                 anies anies hidup nkri
4                                            anies anies
                             ...                        
709                                      politika hhhhhh
710    anies presiden hutang negara lunas dana buzzer...
711    fix putar ganjar anies putar final suara prabo...
712                     muka calon banyakin utang negara
713                                                     
Length: 714, dtype: object

In [35]:
# vectorizer = TfidfVectorizer()
# tf_vector = vectorizer.fit_transform(cleaned_comments)

# Initialize regex tokenizer
tokenizer = RegexpTokenizer(r'\w+')

# Vectorize document using TF-IDF
vectorizer = TfidfVectorizer(lowercase=True,
                        stop_words='english',
                        ngram_range = (1,1),
                        tokenizer = tokenizer.tokenize)

# Fit and Transform the documents
train_data = vectorizer.fit_transform(cleaned_comments)   

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [36]:
col_set = vectorizer.get_feature_names_out()

In [40]:
print(tf_vector.shape)

(714, 1986)


In [41]:
U, s, Vh = randomized_svd(tf_vector, n_components=2, random_state=0)
U.shape, s.shape, Vh.shape

((714, 2), (2,), (2, 1986))

In [39]:
U

array([[ 2.12922271e-02, -1.22807282e-02],
       [-1.14714004e-10, -3.00866611e-10],
       [ 4.71258795e-02, -5.90876084e-02],
       ...,
       [ 5.92845020e-02, -2.92314440e-03],
       [ 6.49388192e-03, -2.94135507e-03],
       [ 0.00000000e+00, -0.00000000e+00]])

In [42]:
s

array([4.45722117, 3.75267074])

In [43]:
Vh

array([[ 7.42387194e-05,  1.01242702e-02,  2.08076598e-03, ...,
         5.62050356e-04,  5.61210346e-03,  1.57734176e-03],
       [-2.61080679e-05, -1.47030413e-02, -2.22376561e-03, ...,
        -8.45258409e-04,  5.95526225e-04, -9.32319180e-04]])

In [44]:
# Define the number of topics or components
num_components=10

# Create SVD object
lsa = TruncatedSVD(n_components=num_components, n_iter=100, random_state=42)

# Fit SVD model on data
lsa.fit_transform(tf_vector)

# Get Singular values and Components 
Sigma = lsa.singular_values_ 
V_transpose = lsa.components_.T

In [46]:
# Print the topics with their terms
terms = vectorizer.get_feature_names_out()

for index, component in enumerate(lsa.components_):
    zipped = zip(terms, component)
    top_terms_key=sorted(zipped, key = lambda t: t[1], reverse=True)[:5]
    top_terms_list=list(dict(top_terms_key).keys())
    print("Topic "+str(index)+": ",top_terms_list)

Topic 0:  ['ganteng', 'anissss', 'anis', 'pilores', 'yudhoyono']
Topic 1:  ['ganteng', 'prediksi', 'pranowo', 'plosok', 'puti']
Topic 2:  ['anissss', 'ahy', 'oleh', 'paham', 'maraukue']
Topic 3:  ['yudhoyono', 'surveynya', 'survenya', 'periode', 'bbm']
Topic 4:  ['prestasi', 'info', 'yudhoyono', 'prediksi', 'pilores']
Topic 5:  ['pranowo', 'mencle', 'ahy', 'subjektif', 'yudhoyono']
Topic 6:  ['pilores', 'anis', 'surveynya', 'anissss', 'rangkai']
Topic 7:  ['mencle', 'prediksi', 'batik', 'pilores', 'bbm']
Topic 8:  ['abal', 'pilores', 'mencle', 'anis', 'prediksi']
Topic 9:  ['batik', 'pranowo', 'pilores', 'yudhoyono', 'surveynya']
